---
sudo: required
dist: xenial

language: c

addons:
  apt:
    packages:
    - python-docutils
    - python-sphinx
    - libmhash-dev

before_install:
  - set -e
  - wget $VARSNIH_TGZ
  - tar -zxf *gz
  - pushd varnish-*/
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

script:
  - make check -j4

env:
  matrix:
    - VARSNIH_TGZ=https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.2.0.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.1.1.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.0.3.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-5.2.1.tgz
    - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-5.1.3.tgz

compiler:
  - clang
  - gcc

matrix:
  allow_failures:
    - env: VARSNIH_TGZ=https://github.com/varnishcache/varnish-cache/archive/master.tar.gz
