---
sudo: required
dist: xenial

language: c

addons:
  apt:
    packages:
    - python-docutils
    - libmhash-dev
    - python-sphinx

before_install:
  - set -e
  - wget $VARSNIH_TGZ
  - tar -zxf varnish-*.tgz
  - pushd varnish-*/
  - ./configure --prefix=/usr
  - make -sj32
  - sudo make install
  - popd

before_script:
  - ./autogen.sh
  - ./configure --prefix=/usr
  - make -j4

env:
  - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.1.1.tgz
  - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-6.0.3.tgz
  - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-5.2.1.tgz
  - VARSNIH_TGZ=https://varnish-cache.org/_downloads/varnish-5.1.3.tgz

script:
  - make check -j4

compiler:
  - clang
  - gcc
